content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  document_creator: 7
  document_reviewer: 8
  news_creator: 15
  news_reviewer: 16
  key_staff_member_creator: 13
  key_staff_member_reviewer: 14
  intranet_user: 12
  internal_page_creator: 11
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_node_type:
  internal_page: 'a:2:{s:8:"view_own";a:1:{i:0;s:13:"intranet_user";}s:4:"view";a:1:{i:0;s:13:"intranet_user";}}'
  internal_document: 'a:2:{s:8:"view_own";a:1:{i:0;s:13:"intranet_user";}s:4:"view";a:1:{i:0;s:13:"intranet_user";}}'
