<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ccg_form_search_api_page_block_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // Ensure the label for the search form gets displayed.
  $form['keys']['#title_display'] = 'before';
  // Add out search icon class to the submit button.
  $form['actions']['submit']['#attributes']['class'] = ['search-icon'];
}
